export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_BY_ID = 'GET_COUNTRIES_BY_ID';
export const SET_STATUS_LOADING = 'SET_STATUS_LOADING';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';